2024-09-30 21:11:22.053 [info] El experimento \"pythonRecommendTensorboardExt\" está activo
2024-09-30 21:11:22.053 [info] El experimento \"pythonTerminalEnvVarActivation\" está activo
2024-09-30 21:11:22.053 [info] El experimento \"pythonTestAdapter\" está activo
2024-09-30 21:11:22.053 [warning] Dir "/home/robrewingco/.pixi/envs" is not watchable (directory does not exist)
2024-09-30 21:11:22.053 [info] Default formatter is set to null for workspace /home/robrewingco
2024-09-30 21:11:22.053 [info] Starting Environment refresh
2024-09-30 21:11:22.053 [info] > pixi --version
2024-09-30 21:11:22.053 [info] > hatch env show --json
2024-09-30 21:11:22.053 [info] cwd: .
2024-09-30 21:11:22.148 [info] Starting Environment refresh
2024-09-30 21:11:22.233 [info] > C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe -I ./.vscode-server/extensions/ms-python.python-2024.14.1-linux-x64/python_files/get_output_via_markers.py ./.vscode-server/extensions/ms-python.python-2024.14.1-linux-x64/python_files/interpreterInfo.py
2024-09-30 21:11:22.233 [info] Environments refresh paths discovered: 1876 milliseconds
2024-09-30 21:11:22.283 [info] Environments refresh paths discovered: 135 milliseconds
2024-09-30 21:11:22.376 [error] [Error: Command failed: C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe -I /home/robrewingco/.vscode-server/extensions/ms-python.python-2024.14.1-linux-x64/python_files/get_output_via_markers.py /home/robrewingco/.vscode-server/extensions/ms-python.python-2024.14.1-linux-x64/python_files/interpreterInfo.py
/bin/sh: 1: C:UsersuserAppDataLocalProgramsPythonPython310python.exe: not found

	at genericNodeError (node:internal/errors:984:15)
	at wrappedFn (node:internal/errors:538:14)
	at ChildProcess.exithandler (node:child_process:422:12)
	at ChildProcess.emit (node:events:531:35)
	at maybeClose (node:internal/child_process:1105:16)
	at Socket.<anonymous> (node:internal/child_process:457:11)
	at Socket.emit (node:events:519:28)
	at Pipe.<anonymous> (node:net:338:12)] {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\python.exe -I /home/robrewingco/.vscode-server/extensions/ms-python.python-2024.14.1-linux-x64/python_files/get_output_via_markers.py /home/robrewingco/.vscode-server/extensions/ms-python.python-2024.14.1-linux-x64/python_files/interpreterInfo.py'
}
2024-09-30 21:11:24.381 [info] > C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe -I ./.vscode-server/extensions/ms-python.python-2024.14.1-linux-x64/python_files/get_output_via_markers.py ./.vscode-server/extensions/ms-python.python-2024.14.1-linux-x64/python_files/interpreterInfo.py
2024-09-30 21:11:24.479 [error] [Error: Command failed: C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe -I /home/robrewingco/.vscode-server/extensions/ms-python.python-2024.14.1-linux-x64/python_files/get_output_via_markers.py /home/robrewingco/.vscode-server/extensions/ms-python.python-2024.14.1-linux-x64/python_files/interpreterInfo.py
/bin/sh: 1: C:UsersuserAppDataLocalProgramsPythonPython310python.exe: not found

	at genericNodeError (node:internal/errors:984:15)
	at wrappedFn (node:internal/errors:538:14)
	at ChildProcess.exithandler (node:child_process:422:12)
	at ChildProcess.emit (node:events:531:35)
	at maybeClose (node:internal/child_process:1105:16)
	at Socket.<anonymous> (node:internal/child_process:457:11)
	at Socket.emit (node:events:519:28)
	at Pipe.<anonymous> (node:net:338:12)] {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\python.exe -I /home/robrewingco/.vscode-server/extensions/ms-python.python-2024.14.1-linux-x64/python_files/get_output_via_markers.py /home/robrewingco/.vscode-server/extensions/ms-python.python-2024.14.1-linux-x64/python_files/interpreterInfo.py'
}
2024-09-30 21:11:24.480 [info] Environments refresh finished (event): 4123 milliseconds
2024-09-30 21:11:24.480 [info] Environments refresh finished (event): 2332 milliseconds
2024-09-30 21:11:24.483 [info] Environment refresh took 4126 milliseconds
2024-09-30 21:11:24.483 [info] Environment refresh took 2336 milliseconds
2024-09-30 21:11:24.491 [info] > pyenv which python
2024-09-30 21:11:24.491 [info] cwd: .
2024-09-30 21:11:24.615 [warning] could not find a pixi interpreter for the interpreter at C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
2024-09-30 21:11:24.632 [info] > C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe -c "import sys;print(sys.executable)"
2024-09-30 21:11:24.641 [warning] could not find a pixi interpreter for the interpreter at C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
2024-09-30 21:11:24.708 [warning] could not find a pixi interpreter for the interpreter at C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
2024-09-30 21:11:24.737 [error] [Error: Command failed: C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe -c "import sys;print(sys.executable)"
/bin/sh: 1: C:UsersuserAppDataLocalProgramsPythonPython310python.exe: not found

	at genericNodeError (node:internal/errors:984:15)
	at wrappedFn (node:internal/errors:538:14)
	at ChildProcess.exithandler (node:child_process:422:12)
	at ChildProcess.emit (node:events:531:35)
	at maybeClose (node:internal/child_process:1105:16)
	at ChildProcess._handle.onexit (node:internal/child_process:305:5)] {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\python.exe -c "import sys;print(sys.executable)"'
}
2024-09-30 21:11:24.784 [info] > pyenv which python
2024-09-30 21:11:24.784 [info] cwd: .
2024-09-30 21:11:24.807 [warning] could not find a pixi interpreter for the interpreter at C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
2024-09-30 21:11:24.816 [warning] could not find a pixi interpreter for the interpreter at C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
2024-09-30 21:11:24.882 [warning] could not find a pixi interpreter for the interpreter at C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
2024-09-30 21:11:25.417 [info] Iniciando el servidor de lenguaje Pylance.
2024-09-30 21:11:25.423 [warning] could not find a pixi interpreter for the interpreter at C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
2024-09-30 21:11:25.435 [warning] could not find a pixi interpreter for the interpreter at C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
2024-09-30 21:11:25.462 [warning] could not find a pixi interpreter for the interpreter at C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
2024-09-30 21:11:26.356 [warning] could not find a pixi interpreter for the interpreter at C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
2024-09-30 21:12:52.024 [info] Discover tests for workspace name: robrewingco - uri: /home/robrewingco/prueba.py
2024-09-30 21:12:54.018 [warning] could not find a pixi interpreter for the interpreter at C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
2024-09-30 21:12:54.027 [warning] could not find a pixi interpreter for the interpreter at C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
2024-09-30 21:13:01.624 [warning] could not find a pixi interpreter for the interpreter at C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
2024-09-30 21:13:03.569 [warning] could not find a pixi interpreter for the interpreter at C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
2024-09-30 21:13:05.252 [warning] could not find a pixi interpreter for the interpreter at C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
2024-09-30 21:13:26.543 [warning] could not find a pixi interpreter for the interpreter at C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
2024-09-30 21:15:05.464 [warning] could not find a pixi interpreter for the interpreter at C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
2024-09-30 21:15:33.396 [warning] could not find a pixi interpreter for the interpreter at C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
2024-09-30 21:15:36.756 [info] Discover tests for workspace name: robrewingco - uri: /home/robrewingco/batalla_naval.py
2024-09-30 21:15:47.173 [warning] could not find a pixi interpreter for the interpreter at C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe
